apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-microservice-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/my-org/caps360-idp.git
    targetRevision: HEAD
    path: helm-charts/golden-path-service
    helm:
      valueFiles:
        - ../../apps/example-microservice/manifests/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-microservice-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/my-org/caps360-idp.git
    targetRevision: HEAD
    path: helm-charts/golden-path-service
    helm:
      valueFiles:
        - ../../apps/example-microservice/manifests/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
